import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gilroySemiBold = localFont({
  // src: "./fonts/GilroySemiBold.woff2",
  src: "../public/fonts/GilroySemiBold.woff2",
  variable: "--gilroySemiBold",
  weight: "100 900",
});
const gilroyMedium = localFont({
  // src: "./fonts/GilroyMedium.woff2",
  src: "../public/fonts/GilroyMedium.woff2",
  variable: "--gilroyMedium",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${gilroySemiBold.variable} ${gilroyMedium.variable}`}>
        {children}
      </body>
    </html>
  );
}
